name: Monitor App Build

on:
  push:
    branches:
      - master

jobs:
  # Build and publish docker image for web app
  build_web-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push monitor app
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: autopacker/monitor-app
          tags: latest
          path: .
